import { IQustion } from './types';

export const QustionData: IQustion[] = [
  {
    id: 1,
    title: '다른 강아지 친구들을 만났을 때, 나의 반응은?',
    answera: '근처도 오지마라 으르렁',
    answerb: '새친구 좋다멍!',
    type: 'EI',
  },
  {
    id: 2,
    title: '집사가 쉬는 날! 집사와의 데이트 장소는?',
    answera: '나는 집,집,집! 집이 좋아',
    answerb: '하루 전부터 두근두근! 나갈 준비 완료',
    type: 'EI',
  },
  {
    id: 3,
    title: '지나가는 인간이 나를 본다면?',
    answera: '저리가라 인간..(질끈)',
    answerb: '나 진짜 귀엽지? 친구하자!',
    type: 'EI',
  },
  {
    id: 4,
    title: '눈 앞에서 집사가 사라진다면?',
    answera: '방금가지 있었는데... 나는 내 할 일 하련다!',
    answerb: '또 시작이네, 여기저기 찾으러 가자!',
    type: 'EI',
  },
  {
    id: 5,
    title: '산책할 때의 나는?',
    answera: '거참.. 아는 길로 가자 집사야..',
    answerb: '저 나비를 쫓아가볼까? 왈왈멍멍',
    type: 'EI',
  },
  {
    id: 6,
    title: '새로운 장난감이 생긴다면?',
    answera: '넌 뭐야? 정체를 밝혀라 약 3초 관심 후 관심 끝!',
    answerb: '나의 왕국에 온 것을 환영해 너는 나의 베스트 장난감',
    type: 'EI',
  },
  {
    id: 7,
    title: '집사가 간식을 들고 처음 보는 훈련을 시도한다?!!',
    answera: '뭐햐? ㅡㅡ (지켜본다)',
    answerb: '킁킁 맛있는 냄새! 일단 따라하고 본다',
    type: 'EI',
  },
  {
    id: 8,
    title: '친구 멍이 같이 사고를 치자고 날 꼬신다면..?',
    answera: '주인한테 혼날거야 난 빼줘 멍~',
    answerb: '나는야 날라리멍, 사고는 치라고 있는 것!',
    type: 'EI',
  },
  {
    id: 9,
    title: '집사와 간식 중에 선택해야 한다면?',
    answera: '하찮은 간식 치워! 집사가 최고다멍',
    answerb: '나의 Pick은 간식이지롱',
    type: 'EI',
  },
  {
    id: 10,
    title: '집사가 외출한다면 나는...?',
    answera: '갔냐?! 왈왈 내가 왕이다',
    answerb: '진짜 간거야? 확인하고 기다린다.',
    type: 'EI',
  },
  {
    id: 11,
    title: '산책 중 화장실이 급하다',
    answera: '참지 않고 바로 쏴-아',
    answerb: '마킹한 곳을 찾아 배변한다.',
    type: 'EI',
  },
  {
    id: 12,
    title: '자동 급식기를 집사가 사왔다',
    answera: '뷔페가.. 요기잇네? ^---^',
    answerb: '아침 점심 저녁! 정확하게 나눠 먹겠어',
    type: 'EI',
  },
];
